name: Angular-CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build app bundle
        run: npm run build:prod

      - name: Rename index for routing
        run: mv dist/hackett-group-challenge/index.html dist/hackett-group-challenge/404.html

      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/hackett-group-challenge/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  